[package]
name = "fteepee-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
btoi = { version = "0.4", default-features = false }
nom = { version = "7", default-features = false }

[features]
default = ["std"]
std = []
